# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ExampleUtilities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleUtilities
  pod 'Utilities', :path => '../'

  target 'ExampleUtilitiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUtilitiesUITests' do
    # Pods for testing
  end

end
